version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - huertohogar-network
    deploy:
      placement:
        constraints:
          - node.role == manager

  usuarios-ms:
    image: nachovn114/huertohogar-usuarios:latest
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/huertohogar_usuarios
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    networks:
      - huertohogar-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  core-ms:
    image: nachovn114/huertohogar-core:latest
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/huertohogar_productos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    networks:
      - huertohogar-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  carrito-ms:
    image: nachovn114/huertohogar-carrito:latest
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/huertohogar_carritos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}
    networks:
      - huertohogar-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  api-gateway:
    image: nachovn114/huertohogar-gateway:latest
    ports:
      - "8080:8080"
    networks:
      - huertohogar-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  huertohogar-network:
    driver: overlay

volumes:
  mysql_data:
