
services:
  mysqldb:
    image: mysql:8.0
    container_name: huertohogar-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - huertohogar-network

  usuarios-ms:
    build: ./usuarios-microservice
    container_name: usuarios-ms
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/huertohogar_usuarios
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - mysqldb
    networks:
      - huertohogar-network

  core-ms:
    build: ./core-microservice
    container_name: core-ms
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/huertohogar_productos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - mysqldb
    networks:
      - huertohogar-network

  carrito-ms:
    build: ./carrito-microservice
    container_name: carrito-ms
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/huertohogar_carritos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - mysqldb
    networks:
      - huertohogar-network

networks:
  huertohogar-network:
    driver: bridge

volumes:
  mysql_data: